language: go
sudo: false
go:
  - "1.15.x"
  - master
os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - arm64

jobs:
  allow_failures:
    - go: master
  fast_finish: true
  exclude:
    - os: windows
      go: master
    - arch: arm64
      os: osx
    - arch: arm64
      os: windows


before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        choco install mingw -y;
        export PATH=/c/tools/mingw64/bin:"$PATH";
    fi

script:
  - go test -race ./formatter -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)